services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    volumes:
      - ./weather_data:/data
      - ./weather_data/schedule.yaml:/data/schedule.yaml:ro
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./scraper
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile.scraper

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8899:8000"
    volumes:
      - ./shared_data:/data
    depends_on:
      - scraper
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./web
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile.web

volumes:
  weather_data:
